version: '3.3'
services:
  fronis_db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    restart: always
    environment:
      MYSQL_DATABASE: 'fronis'
      MYSQL_USER: 'fronis'
      MYSQL_PASSWORD: 'fronis'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3316:3316'
