version: '3.3'
services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DATABASE: 'fronis'
      POSTGRES_USER: 'fronis'
      POSTGRES_PASSWORD: 'fronis'
      POSTGRES_ROOT_PASSWORD: 'password'
    ports:
    - '5432:5432'
