### all players
GET {{baseUrl}}/admin/api/players

### all players query
GET {{baseUrl}}/admin/api/players?query=st

### player id 1
GET {{baseUrl}}/admin/api/players/1


### player id 1
PUT {{baseUrl}}/admin/api/players/1
Content-Type: application/json

{
  "firstName": "Severin",
  "lastName": "renamed",
  "playerNumber": "29"
}


### player id 5684 (fails)
PUT {{baseUrl}}/admin/api/players/17
Content-Type: application/json

{
  "firstName": "Nicolas",
  "lastName": "Kistler",
  "playerNumber": "29"
}

